### ISSUE TITLE
javaExampleGenerator问题

### ISSUE THREAD

**Issue by zhangleijie** [yangjianzhou/mybatis-generator#1]
哥们这个工程你测试过吗？ 
[ERROR] XML Parser Error on line 27: 必须声明元素类型 "javaExampleGenerator"。
[ERROR] XML Parser Error on line 43: 必须为元素类型 "table" 声明属性 "mapperName"。
[ERROR] XML Parser Error on line 44: 元素类型为 "context" 的内容必须匹配 "(property*,plugin*,commentGenerator?,jdbcConnection,javaTypeResolver?,javaModelGenerator,sqlMapGenerator,javaClientGenerator?,table+)"。
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] -----

http://maven.apache.org/xsd/maven-4.0.0.xsd  这个文件中就没有javaExampleGenerator 节点

**Comment by yangjianzhou** [comment]
哪里有什么问题？

**Comment by yangjianzhou** [comment]
这个项目是通过验证的，这个项目的主要目的是验证自己生成的jar包（org.mybatis.generator:mybatis-generator-core:1.3.7.2），是否可以将model和example生成在不同的package里面。这个jar没对外开发，相关功能已经被merge到官方的mybatis-generator-core的master了，今年应该会发布。
